title:            Correlated Causation
description:      A data driven approach to venture.
logo:             cc-logo.png
disqus_shortname:
search:           false
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://correlatedcausation.com

# Owner/author information
owner:
  name:           Jamie Davidson
  avatar:         jamie-davidson-photo.jpg
  email:          jdavidson@redpoint.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        jamiedavidson
  facebook:
  github:         jdavidson
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+JamieDavidson

# Analytics and webmaster tools stuff goes here
google_analytics: UA-46114040-1
google_verify:    ASxxsxPEOACZZ-O3-Q-WL0er25dh-jY1hiu_fgWsMv4
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:      FDB2F168D492C322576BF5DA29F4981E

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Articles
    url: /articles

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]


prose:
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
      - name: "description"
        field:
          element: "text"
          label: "description"
